### ISSUE TITLE
Code update :N-N scenario

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1003]
- [ ] Need to add N-N scenario automation

- [ ] Validate the BMC / PNOR version similar to what we had for old code update / Master way of checking. ( Validate BMC Version )

https://github.com/openbmc/openbmc-test-automation/blob/master/extended/code_update/code_update_utils.robot

Please validate for both BMC and PNOR

**Comment by gkeishin** [comment]
https://gerrit.openbmc-project.xyz/#/c/6839/

**Comment by charleshofer** [comment]
That change doesn't implement a true N-N scenario. It might even do N+1 or N-1 depending on the state of the machine you run it on. The change checks to see if the image that you would like to update to is already active. If it is active, it gives the image priority, and then reboots the BMC to make sure that image is running. It doesn't do a code update. That change is only mean to fix SW402308.

**Comment by gkeishin** [comment]
@sivassrr ^^

**Comment by gkeishin** [comment]
This one what we can do is update and then expect error , i think we should have a test for it..

**Comment by charleshofer** [comment]
> This one what we can do is update and then expect error , i think we should have a test for it..
I don't think this is a test case worth doing. We'll be able to upload the image just fine, but the information in the software manager won't change. Setting the RequestedActivation of the image to Active won't run a code update because the image will already be active. We won't even get an error. The only reason that automation currently gives us an error is because it is expecting the image's Activation to be in the "Ready" state and it is finding that it's in the "Active" state.

**Comment by charleshofer** [comment]
However, validating the BMC version sounds like a worthwhile test case to write.

**Comment by gkeishin** [comment]
Sounds good to me.. let code that one up and update in the RQM as well

**Comment by charleshofer** [comment]
I don't think it needs to be changed in RQM, I think it just needs to be a check that happens within our current code update test cases.

**Comment by charleshofer** [comment]
https://gerrit.openbmc-project.xyz/#/c/6888/

**Comment by gkeishin** [comment]
Thanks @charleshofer
