### ISSUE TITLE
Collecting FFDC using dReport instead of our MyFFDC

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1118]
@gkeishin 
Can we move to dReport which will be similar to customer like FFDC collection instead of our MyFFDC.?

**Comment by gkeishin** [comment]
This we need to discuss with @micwalsh as well since DVT also uses the common FFDC, if we both agree on it then we will move portion of the FFDC.the dReport collects on the BMC parts but our FFDC goes beyond BMC but also host.. so there is no replacement for the FFDC we got but we can tweak a bit to add the dReport in our FFDC.

**Comment by sivassrr** [comment]
This need to be discussed in our Test group open community call. So will leave it open.
