### ISSUE TITLE
GUI: Automation:  Support for Non-headerless systems support

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#1246]

**Comment by sivassrr** [comment]
@samahaba we can discuss on this today if possible. Basically we need to have support for non-headerless system.

**Comment by samahaba** [comment]
See the non-headerless  that is headeless browser is already support and working fine on Linux system, and with header browser working fine on Windows OS, please find below the URL 

http://tulpok01p4.aus.stglabs.ibm.com:8080/jenkins/job/GUI_Test_Execution/58/console

Here the problem only in Mac OS that we need identify the proper solution, whether we need to do for head or headless browser to launch on Mac OS . That we will identify the suitable solution for the same.

**Comment by samahaba** [comment]
Here the provided solution is just launch OpenBMC GUI with Header browser on Mac OS but Issue is provided header less browser on Mac OS that it was original problem and expectation that non header / headerless browser  should  both work on Mac OS and at the final stage of discussion that all are expected and concluded that (customer like Intel, Microsoft, Dell and Google) will expect that our OpenBMC GUI should launch and we should provide the support for both header and header less browser support for all type of OS like WINDOWS/LINUX/MAC/RedHAT Linux/Obunto all most all type of OS, because customer will have all type of OS.

**Comment by samahaba** [comment]
So issue is closed virtually, because the actual issue was raised against that we need to provide virtual browser support and header browser support both for all the OS types Linux/Windows/Obountu/MacOS/RedHat Linux. but here the solution is only provided for just launching of header mode browser only for Mac OS, and for Windows platform it is already provided , but what about other OS types and **what about solution for launching of headless browser for MAC OS**
