### ISSUE TITLE
[Automation] Test Fan Speed Toggling

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#139]
For now the test fan use case is empty dummy.  

As per discussion
Palmetto didn’t have fan support however for Barreleye looks like eventually we'll be write the fan controller code.

In fact Fan code exists from Foxconn as per Chris.  FVT would be to support the interface and anything the client can toggle. 

As from the current code..  https://github.com/openbmc/skeleton/blob/a7ac805b407617f7a83eb152ff823f44d243a9b2/pyfanctl/fan_control.py#L25

which have the method only for setting the fan speed to MAX . so we can't do anything on it toggling.

How ever for history and placeholder creating this tracking github for future when the supports comes in,

**Comment by ssombar** [comment]
Steven Sombar [08:43]
@msbarth hi GM!   On OpenBMC systems can user customer toggle fan speeds?  
Matthew Barth [08:43]
no, not directly allowed

**Comment by ssombar** [comment]
I think we can close this Issue

**Comment by msbarth** [comment]
@gkeishin @ssombar 
Could you clarify the intention of this issue and `Fan Speed Toggling` ?
Its never intended that a customer is allowed to change fan speeds, but there is a procedure that can be followed to do manual fan speed control.

**Comment by ssombar** [comment]
I think years ago we allowed customers to toggle fan speeds for noise purposes.   
But I'd like to know the procedure to do manual fan speed control, perhaps I can enhance an existing TC.

**Comment by msbarth** [comment]
Well all that'd be able to be verified is that fan monitor doesnt mark fans nonfunctional when changing fan speeds...unless you plan to do manual fan blocking, etc.. To do manual fan control involves stopping the fan control application, so you wont be able to test the algorithm itself. Also, you would need to make sure no workload is placed on the system while doing this since no temperatures would be monitored (and fan speeds adjusted accordingly) since fan control would be stopped. Actually...this may help to verify the fan controller chip driver since we've seen some issues with this in the past

To do manual fan control:
```#Log into BMC
#Power on system (or already have system powered on)
#Stop fan control application service
> systemctl stop phosphor-fan-control@0.service
#Find hwmon instance for the fan controller chip
> mapper get-service /xyz/openbmc_project/sensors/fan_tach/fan0_0
    xyz.openbmc_project.Hwmon-[some hash].Hwmon1
#Use busctl to set the target speed property in hwmon instance, do this for each fan instance that has a target property (example for a RPM based controller):
> busctl set-property xyz.openbmc_project.Hwmon-[some hash].Hwmon1 /xyz/openbmc_project/sensors/fan_tach/fan0_0 xyz.openbmc_project.Control.FanSpeed Target t [RPM]
```
At this time, its required to place all fans to the defined max speed prior to restarting the fan control application service
```#Start fan control application service
> systemctl start phosphor-fan-control@0.service
```

You can then use REST to verify the feedback speeds, but should probably also verify the target and feedback speeds out of sysfs as well.
```#On BMC, determine the fan controller hwmon instance directory(max31785a for witherspoon)
> grep -ir max31785a /sys/class/hwmon/hwmon*
    hwmon9/name:max31785a
#Check sysfs target speed for all fans
> tail -v /sys/class/hwmon/hwmon9/fan*_target
#Check sysfs input speed for all fans
> tail -v /sys/class/hwmon/hwmon9/fan*_input
```

Also remember that the input(feedback) speeds will never equal the target, they should be within a certain range which is where verifying they are correct becomes difficult since this deviation from the target speed is defined in the fan monitor application's yaml and could change at anytime, etc...
