### ISSUE TITLE
Support required for X-Auth-Token for puts/posts/deletes

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc-test-automation#1493]
When we move to bmcweb as the REST server, it requires the X-Auth-Token to be passed in with the header on a put/post/delete, though it doesn't hurt to always be passed in.  I'm not sure if robot already supports this or not, so I figured I should bring it up.

When I changed it in openbmctool.py, it was like:

```
r = mysess.post('https://'+host+'/login', headers=jsonHeader, json = {"data": [username, pw]}, verify=False, timeout=30)
cookie = r.headers['Set-Cookie']
match = re.search('SESSION=(\w+);', cookie)
if match:
    xAuthHeader['X-Auth-Token'] = match.group(1)
```
and then pass that xAuthHeader in with the post, etc

with curl, if you use the -i on the login it will give you the token:
```
Set-Cookie: SESSION=pqh8HrJcmyg6tNbmbi1q; Secure; HttpOnly
```
and then pass that in with future posts:
```
... -H "X-Auth-Token: pqh8HrJcmyg6tNbmbi1q" ...
```

**Comment by gkeishin** [comment]
Yup that correct. We are working on it to move the automation entirely to Redfish https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/16317/

We have intermediate code already in https://github.com/openbmc/openbmc-test-automation/blob/master/lib/redfish_client.robot#L94

but haven't used since it causes more breakage than actually fix in the test. So we will be going ahead with above commit and move test code to redfish when in pieces when supported modules are available

**Comment by spinler** [comment]
We're going to phase in bmcweb.  first stage is use to just replace the REST server, and second is to move everything to redfish.  So you would still need to do this authentication without redfish, just to make it clear.

**Comment by gkeishin** [comment]
Code merged
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/17476/
