### ISSUE TITLE
IPMI User management

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#1523]
- [x] Test plan
- [x] Test and verify
- [x] Automation

**Comment by rahulmah** [comment]
**Test cases for IPMI user management testing**

- [ ] Get User name
1. Execute get user name command using IPMItool.
2. User name list should get displayed as output of above command.

- [ ] Set User name
1. Execute set user name command using IPMItool.
2. New user name should get set on the system. 

- [ ] Get User access
1. Execute get user access command using IPMItool.
2. User access setting should get displayed as output of the command.

- [ ] Set User access
1. Execute set user access command using IPMItool.
2. New user access setting should get set on the system.

- [ ] Set User password
1. Execute set user password command using IPMItool.
2. New user password should get set on the system.

- [ ] Set Invalid User password
1. Set invalid user name and password command using IPMItool.
2. Both invalid user name and password should not get set and appropriate error should be displayed.

**Comment by rahulmah** [comment]
@tomjoseph83 : Please review above test cases which we planned for testing IPMI user management.

**Comment by rahulmah** [comment]
@tomjoseph83 : I have added test cases as suggested. https://github.com/openbmc/openbmc-test-automation/issues/1523#issuecomment-459268555

**Comment by rthomaiy** [comment]
I am not sure about the scope of the test cases for this topic (but limiting it to IPMI, at the same time from whole BMC). Please look at the following too
1. Create / Delete user through redfish, and try using the same in IPMI  (vice versa)
2. Update the password in redfish, and see whether it's getting used in IPMI (similarly others enable / priv) (vice versa)
3. Channel command privilege are working as per the channel (but at this point of time this differentiation can't be made due to architecture limitations, but ok to write test case and mark it as failed, rather than skipping the same)
4. 


Few comments on the existing one
1. dictionary password won't be accepted (we are using pam_cracklib) and hence password, abc123 will not be accepted. (test cases using this as valid password has to be updated).
2. user id 1 --> treating this as root. At this point of time we are having root user in ipmi. But direction we are going is to create user using host interface if available / any other interface (i.e. root shouldn't be used).
3. Few things which are not following as per IPMI Spec (for security reason)
-  Null username / password is not supported
-  test password won't return password size mismatch for security reason
4. Privilege has to be tested against the channel, i.e. if for LAN 1 it is set to NO_ACCESS, then restrictions apply for LAN1 only and not for LAN2 (as mentioned architecture doesn't allow it to detect the channel where the commands are executed and by default assume LAN1).
5. Also test session privilege execution (i.e. Administrator user can request max privilege as operator and establish session for operator in which case administrative command shouldn't be executed)
6. test user name / privilege lookup fileds options in establishing RMCP+ connections and test it out
7. Try to change session privilege and execute other commands and make sure it doesn't exceed user privilege / requested max privilege during RAKP messages (Not sure how you can test this using ipmitool)

**Comment by rthomaiy** [comment]
Delete user test from ipmitool can be added too

**Comment by gkeishin** [comment]
- [ ] First drop changed https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/18088/

**Comment by rahulmah** [comment]
Please find my comments below: 

I am not sure about the scope of the test cases for this topic (but limiting it to IPMI, at the same time from whole BMC). Please look at the following too

1. Create / Delete user through redfish, and try using the same in IPMI  (vice versa)
2. Update the password in redfish, and see whether it's getting used in IPMI (similarly others enable / priv) (vice versa)
3. Channel command privilege are working as per the channel (but at this point of time this differentiation can't be made due to architecture limitations, but ok to write test case and mark it as failed, rather than skipping the same)

[Rahul] - This was designed to cover only IPMI. But you have good point and I have created a sperate story(https://github.com/openbmc/openbmc-test-automation/issues/1605) for the same.

Few comments on the existing one

1. dictionary password won't be accepted (we are using pam_cracklib) and hence password, abc123 will not be accepted. (test cases using this as valid password has to be updated).
[Rahul] - Done
2. user id 1 --> treating this as root. At this point of time we are having root user in ipmi. But direction we are going is to create user using host interface if available / any other interface (i.e. root shouldn't be used).
[Rahul] - When are we planning to take root user out? If the time line is long, I would say lets keep root user user related test cases till we dont take root user out.
3. Few things which are not following as per IPMI Spec (for security reason)

* Null username / password is not supported
[Rahul] - Added respective testcases above.

* test password won't return password size mismatch for security reason
[Rahul] - Okay. Will keep a note of it. I was not having testcase for testing user password using test command it. I have added it now.

4. Privilege has to be tested against the channel, i.e. if for LAN 1 it is set to NO_ACCESS, then restrictions apply for LAN1 only and not for LAN2 (as mentioned architecture doesn't allow it to detect the channel where the commands are executed and by default assume LAN1).

5. Also test session privilege execution (i.e. Administrator user can request max privilege as operator and establish session for operator in which case administrative command shouldn't be executed)

6. test user name / privilege lookup fileds options in establishing RMCP+ connections and test it out
[Rahul] - Added a check for in channel test cases.

7. Try to change session privilege and execute other commands and make sure it doesn't exceed user privilege / requested max privilege during RAKP messages (Not sure how you can test this using ipmitool)
[Rahul] - Is it a functional test or unit test? Can you please help with the steps?

8. Delete user test from ipmitool can be added too
[Rahul] - I dont believe we can delete IPMI user using IPMI. We can just overwrite. Correct me if I am wrong. But yes we can have this in Redfish and IPMI combination for user managemnet.

**Comment by gkeishin** [comment]
Commits 
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/18548/
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/18560/
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/18562/
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/18550/
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/18585/
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/18567/
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/18466/
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/18502/
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/18088/
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/18235/

**Comment by rthomaiy** [comment]
> @rthomaiy : **Please find my comments below:**
> 
> 1. Create / Delete user through redfish, and try using the same in IPMI  (vice versa)
> 2. Update the password in redfish, and see whether it's getting used in IPMI (similarly others enable / priv) (vice versa)
> 3. Channel command privilege are working as per the channel (but at this point of time this differentiation can't be made due to architecture limitations, but ok to write test case and mark it as failed, rather than skipping the same)
> 
> `[Rahul] - This was designed to cover only IPMI. But you have good point and I have created a separate story(https://github.com/openbmc/openbmc-test-automation/issues/1605) for the same.`
> 
> Few comments on the existing one
> 
> 1. dictionary password won't be accepted (we are using pam_cracklib) and hence password, abc123 will not be accepted. (test cases using this as valid password has to be updated).
>    `[Rahul] - Done`
> 2. user id 1 --> treating this as root. At this point of time we are having root user in ipmi. But direction we are going is to create user using host interface if available / any other interface (i.e. root shouldn't be used).
>    `[Rahul] - When are we planning to take root user out? If the timeline is long, I would say lets keep root user user related test cases till we dont take root user out.`
`[Richard] - should look in to this, once few priorities got sorted out. What i am trying to say is, we don't need to add any test case saying root user privielge should not be changed, or root user can't be deleted
(At this point of time we don't allow, as we are using linux uid 0 "root", but in reality if it is any other user name in user id 1, then it can be deleted too `
> 3. Few things which are not following as per IPMI Spec (for security reason)
> 
> * Null username / password is not supported
>   `[Rahul] - I would like to know what do you mean by null username. Do you mean setting user name to ""? if that the case, we are allowed to send the username as "". Only thing is that we delete the user, if we try to set user name to "". For null password I have added the test case above`
`[Richard]  - i refer the anonymous user, which won't have any user name. We can't set this use set user name, and as per IPMI spec, it will be in any one of the user id, generally user id 1, which we are not supporting. Not  set username command with "" will delete the user`
> * test password won't return password size mismatch for security reason
>   `[Rahul] - Okay. Will keep a note of it. I was not having test case for testing user password using test command it. I have added it now - Verify user password using test command.`
> 
> 1. Privilege has to be tested against the channel, i.e. if for LAN 1 it is set to NO_ACCESS, then restrictions apply for LAN1 only and not for LAN2 (as mentioned architecture doesn't allow it to detect the channel where the commands are executed and by default assume LAN1).
>    `[Rahul] - Added test case above (e.g. Set administrator and No access privilege for different channels and Verify) to cover them up. `
> 2. Also test session privilege execution (i.e. Administrator user can request max privilege as operator and establish session for operator in which case administrative command shouldn't be executed)
>    `[Rahul] - You mean new Operator level user should not be able to run administrator level IPMI command.  If yes, we have already covered it.`
`[Richard] - Not only that. an Administrator privilege user can create a session with operator privilege itself. In that case, administrative privilege shouldn't be executed. You can do this in ipmitool using -L option`
> 3. test user name / privilege lookup fields options in establishing RMCP+ connections and test it out
>    `[Rahul] - Added a check for in channel test cases.`
> 4. Try to change session privilege and execute other commands and make sure it doesn't exceed user privilege / requested max privilege during RAKP messages (Not sure how you can test this using ipmitool)
>    `[Rahul] - Is it a functional test or unit test? Can you please help with the steps?`
`[Richard] - As i mentioned not sure, how to test the same using ipmitool`
> 5. Delete user test from ipmitool can be added too
>    `[Rahul] - What command we need to use to delete the IPMI user? If I am correct, we can run IPMI command to set user name to null for deleting it - `
>    `user set username <id> ""`
`[Richard] - yes, that's correct`

**Comment by gkeishin** [comment]
Commits: 
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc-test-automation/+/18641/

**Comment by gkeishin** [comment]
Split worked https://github.com/openbmc/openbmc-test-automation/issues/1528

**Comment by rahulmah** [comment]
Issued logged -

>1. **Able to run IPMI command with user with IPMI messaging disabled and no access privilege**
https://github.com/openbmc/phosphor-host-ipmid/issues/125

> 2. **Unable to enable IPMI user with recent build**
https://github.com/openbmc/phosphor-host-ipmid/issues/127

> 3. **Disabled IPMI root user is able to run IPMI command**
https://github.com/openbmc/phosphor-host-ipmid/issues/128

>4. **IPMI tool allowing to set different privilege for root user** - Closed
https://github.com/openbmc/phosphor-host-ipmid/issues/123 

>5. **User list command without channel number is failing with inband -IPMI** - Closed
https://github.com/openbmc/phosphor-host-ipmid/issues/124

**Comment by gkeishin** [comment]
Please create additional task for user priv bad path and verifying with Richard.
