### ISSUE TITLE
GUI: LDAP Test Plan

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#1567]
Test LDAP features in GUI

Dev Story - https://github.com/ibm-openbmc/dev/issues/177

https://github.com/openbmc/phosphor-webui/issues/38
https://github.com/openbmc/phosphor-webui/issues/39

**Comment by gkeishin** [comment]
Due to complexity of LDAP testing. Since we are taking care of the back end, frontend GUI we will largely due manually to verify the feature.

**Comment by sivassrr** [comment]
- [ ] Login / Authorization using GUI - 1

- [ ] Group creation and privilege all combination  test - 2

**Comment by sivassrr** [comment]
All test cases generated based on the available prototype on 14 Jun 2019

**Expectation:**
•	Verify LDAP GUI page works fine in all supported browser

**Test Cases Scenarios:**


**(1) Ability to reach LDAP configuration page:**
Ability to select  “Access Control” and LDAP related sub-menu  LDAP Configuration  - Applicable to both host power on / power off state

•	Verify “Access Control” main button is selected and clickable
•	Verify  sub menu list display
•	Verify “LDAP Configuration” or  “LDAP role group settings” selected

**(2) LDAP Role Group Settings Page related TCs:**

Ability  to select/de-select the check box “Enable LDAP authentication”
•	Verify On Disable Enable LDAP authentication
o	Verify all entries are greyed out on Disable – as shown below

![image](https://user-images.githubusercontent.com/19144129/59499678-8732f800-8eb5-11e9-9fe3-11979ed1a051.png)

•	Verify on Enable the button “Enable LDAP authentication” all fields are allowed to enter / modify – as shown below

![image](https://user-images.githubusercontent.com/19144129/59499781-b6496980-8eb5-11e9-99be-52fcc32c1de8.png)

**(3)  Ability to select / de-select  the check box button “ Secure LDAP using SSL”**

•	Verify on enable “Secure LDAP using SSL” check box button capable of clicking the URL “Go to SSL certificates” and on-click it should take as to the right page
•	Verify if certificates files already uploaded should be visible as shown below

![image](https://user-images.githubusercontent.com/19144129/59499994-3374de80-8eb6-11e9-9539-e80ca88d6385.png)


**(4) Selecting LDAP Server Type:**
•	Verify LDAP server type is able to select using Radio button
![image](https://user-images.githubusercontent.com/19144129/59500183-8cdd0d80-8eb6-11e9-8210-884206ba9647.png)

![image](https://user-images.githubusercontent.com/19144129/59500263-b5fd9e00-8eb6-11e9-970a-68f661a94f29.png)

![image](https://user-images.githubusercontent.com/19144129/59500306-cd3c8b80-8eb6-11e9-9563-d53ccfdd8641.png)

 **(5) Role Group Scenarios:**

Below is the text related to the updated design received:
1.Role Group Name will be a textbox rather than a dropdown
2. `Submit` button in Settings section will be labeled as `Save`
3. `Clear` button in Settings section will be labeled as `Reset`
4. The Layout may be slightly different in the alignment of buttons. The prototype is not perfect

![image](https://user-images.githubusercontent.com/19144129/59500514-3b814e00-8eb7-11e9-8e1a-eebc92092cda.png)

**Comment by sivassrr** [comment]
Word document attached: 

[LDAP GUI Test plan.docx](https://github.com/openbmc/openbmc-test-automation/files/3290097/LDAP.GUI.Test.plan.docx)

**Comment by derick-montague** [comment]
@sivassrr - the `Access Control` navigation section for testing this is dependent on https://github.com/ibm-openbmc/dev/issues/619.

**Comment by derick-montague** [comment]
The reset button is only for clearing any changes made to the LDAP settings. The Group display is only empty if:

1. There aren't any groups
1. LDAP is disabled
![image](https://user-images.githubusercontent.com/1183515/59528696-8fcf0280-8ea4-11e9-88bb-cdeceedcb184.png)

**Comment by sivassrr** [comment]
Highlighted test case added based on the revised designed provided over slack as follows: ```Below is the text related to the updated design received:
1.Role Group Name will be a textbox rather than a dropdown
2. Submit button in Settings section will be labeled as Save
3. Clear button in Settings section will be labeled as Reset
4. The Layout may be slightly different in the alignment of buttons. The prototype is not perfect```

**Comment by rahulmah** [comment]
@sivas.srr: Thanks for creating test pan for LDAP GUI testing. Below are my some comments. 
1. Please divide test scenarios into test cases so that we have correct test count.
2. We need to have some end to end test cases also. Example - 
Verify LDAP user login success after configuring LDAP with correct OpenLDAP setup details.
Verify LDAP user login success after configuring LDAP with correct AD setup details.
3. Test cases which check group behavior. E.g. How group user will behave after configuring.

**Comment by sivassrr** [comment]
[LDAP GUI Test planV1.docx](https://github.com/openbmc/openbmc-test-automation/files/3323946/LDAP.GUI.Test.planV1.docx)

**Comment by gkeishin** [comment]
Thanks @sivassrr closing this task

**Comment by sivassrr** [comment]
Sl # | Test Case - Title
-- | --
1 | Browser support -  Verify   LDAP GUI page works fine in all supported browser
2 | Ability to reach LDAP   configuration page - Verify “Access Control” main button is selected and   clickable
3 | Ability to reach LDAP   configuration page - Verify  sub menu   list display
4 | Ability to reach LDAP   configuration page - Verify “LDAP Configuration” or  “LDAP role group settings” selected
5 | Ability to reach LDAP   configuration page - Verify On Disable Enable LDAP authentication
6 | LDAP Role Group Settings Page   related TCs -  Ability  to select/de-select the check box “Enable   LDAP authentication”
7 | LDAP Role Group Settings Page   related TCs -    Verify on Enable the   button “Enable LDAP authentication” all fields are allowed to enter /   modify
8 | Ability to select /   de-select  the check box button “   Secure LDAP using SSL” -  Verify on   enable “Secure LDAP using SSL” check box button capable of clicking the URL   “Go to SSL certificates” and on-click it should take as to the right page
9 | Ability to select /   de-select  the check box button “   Secure LDAP using SSL” -  Verify if   certificates files already uploaded should be visible as shown below
10 | Selecting LDAP Server Type:   -  Verify LDAP server type is able to   select using Radio button
11 | Selecting LDAP Server Type:   -  Verify elements of LDAP   configurations is editable
12 | Selecting LDAP Server Type: -  Verify all elements displayed corresponding   value of LDAP server type which was entered earlier
13 | Selecting LDAP Server Type:   -  Verify on click “Reset” Button all   values in the LDAP configuration text box elements cleared
14 | Selecting LDAP Server Type:   -  Verify on click “Save” Button all   values stored in the LDAP configuration file ( /etc/nslcd.conf )
15 | Role Group Scenarios: -  Verify the text “Role Groups” displayed
16 | Role Group Scenarios: -  Verify display of elements “Add role group”   and “Remove role group” with trash icon
17 | Role Group Scenarios: - Verify   display of element check box to select all group name / group privileges rows
18 | Role Group Scenarios: -  Verify display of text “Group name” and   “Group privilege” at the right column
19 | Role Group Scenarios: -  Verify on clicking element “Add role group”   text box to enter “Role Group Name” value appears
20 | Role Group Scenarios: -   Verify on clicking element “Group   Privilege”  a drop down menu appears to   select one of the element from the list    “Administrator/Operator/User/Callback”
21 | Role Group Scenarios: - Verify   after entering required elements value then capable of saving the same using   “Save” button element
22 | Role Group Scenarios: - Verify role group   content from GUI and Redfish are same.
23 | Role Group Scenarios: -   Verify on click “Reset” Button all values   in the “Role groups” elements cleared
24 | Role Group Scenarios: -    Verify “Remove role group” element is not   enabled when check box button as shown is not-selected
25 | Role Group Scenarios: -    Verify “Remove role group” element is   enabled when check box button as shown is selected
26 | Role Group Scenarios: -  Verify “Remove role group” element is   enabled when check box button  is   selected and selected all rows of    group name with group privilege
27 | Role Group Scenarios: - Verify   LDAP user with Admin privilege able to do BMC reboot
28 | Role Group Scenarios: - Verify LDAP user   with Admin privilege able to do host power on/off
29 | Role Group Scenarios: -   Verify LDAP user with Admin privilege able   to clear event logs
30 | Role Group Scenarios: -  Verify LDAP user with Operator privilege   able to do host power on / off
31 | Role Group Scenarios: -  Verify LDAP user with User privilege read   the inventory / sensors
32 | Role Group Scenarios:   -   Verify LDAP user with Callback  read the inventory / sensors
33 | Bad Path Scenarios: -  Verify LDAP Login fails if wrong values   entered in LDAP configuration element
34 | Bad Path Scenarios: -    Verify LDAP login fails if unknown   LDAP group name is entered
35 | Bad Path Scenarios: -   Verify LDAP login fails if LDAP user is   not listed in the LDAP server
36 | Cosmetics: -  Verify no typo / mis-spelling in the LDAP   page
37 | Cosmetics: -  Verify appropriate Capitals and   non-capitals used through out the page
38 | LDAP Login Verification: End to   End: -  Verify LDAP user login success   after configuring LDAP with correct OpenLDAP setup details.
39 | LDAP Login Verification: End to   End: -  Verify LDAP user login success   after configuring LDAP with correct AD setup details.
