### ISSUE TITLE
[Automation] Code update on Palmetto failing due to ping failure after warm reset

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc-test-automation#169]
In code update, warm reset is triggered to prepared the system before code update. At present we have wait time of 5 minutes for system to become pingable after warm reset. In Palmetto, system is taking long time to become pingable after warm reset.  Seem like wait time need to be increase in

```
Initiate Code update BMC :: BMC code update process initiation        | FAIL |
Keyword 'Verify Ping and REST Authentication' failed after retrying for 5 minutes. The last error was: Ping Failed
```

Kernel logs from the system
[dmesg.txt](https://github.com/openbmc/openbmc-test-automation/files/529263/dmesg.txt)

**Comment by gwshan** [comment]
5 minutes shoud be long enough. please attach the kernel log.

2016年10月14日 下午7:15，"Rahul Maheshwari" <notifications@github.com>写道：

**Comment by gkeishin** [comment]
Looks like post reboot the Ping initially succeeded and REST login was failing...  post few retries the network didn't came up for longer then expected... that seems like that.. Yeah.. @rahulmah could say more to this..

**Comment by rahulmah** [comment]
@gwshan : Please find attached dmesg logs from system.
[dmesg.txt](https://github.com/openbmc/openbmc-test-automation/files/529267/dmesg.txt)

**Comment by gwshan** [comment]
@gkeishin, thanks for the explanation.

@rahulmah, there are no NCSI channel failover according to the attached kernel log in comment#13. Any ideas on what the warm reset is for?

**Comment by rahulmah** [comment]
I believe warm reset is there to prepare system is good state before starting code update.

**Comment by gwshan** [comment]
Checked with @rahulmah offline, the warm reset is system reboot. We observed different MAC addresses are assigned to eth0 before/after the reboot, which means network change and the whole network needs some time to be stable. Before that, BMC isn't reachable.

On the other hand, the potential issue might be same MAC address is set to multiple BMCs that seats in same LAN. Please check it out and avoid it.

I don't see there is anything wrong with NCSI.

**Comment by rahulmah** [comment]
Opened issue https://github.com/openbmc/openbmc/issues/673. for MAC Address change problem after reboot. I believe this is what causing ping failure after reboot.

**Comment by gkeishin** [comment]
So we can close this then ... Good catch..

**Comment by mdmillerii** [comment]
How did you determine the warm reset had completed initially?  Do you just sleep for some time then start the ping?

Is it possible a flash image was pending in `/run/initramfs` that caused the `warmReset` to execute the flash write?  During the `/run/initramfs/update` script execution the bmc will continue to ping because the Linux kernel is still running.  You will also be able to observe progress on the console, but no input will be acted upon.   When the system does come back up it will reconfigure.

This can be avoided by calling `Abort` on the `org.openbmc.control.BmcFlash` image before attempting to call `PrepareForUpdate`.   It could be argued to make `PrepareForUpdate` error if there are pending updates suggesting `Abort` or `warmReset`.
