### ISSUE TITLE
OpenBMC Test setup for Windows ? 

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#2120]
If anyone can try and help the set of packages and working instruction would be awesome. 

We ran quite long time ago, but I dont have those setup anymore.

**Comment by peterp-ibm** [comment]
Oct 13:
(1) ipmiitool for windows (specifically windows 10 pro) :  It took a few days experimenting with cygwin packages to be able to build a ipmitool.exe that has lanplus option working.   https://github.com/ipmitool/ipmitool and https://cygwin.com/install.html

(2) with import/use of grp skipped based on platform.system() == windows since grp is additional info in reports which is not essential for test execution.
Seeing 2 issues
(2a)  **failed: AttributeError**: module 'signal' has no attribute 'SIGALRM'. And
**failed: AttributeError**: module 'signal' has no attribute 'SIGUSR1'

Windows OS does not have these signals implemented so investigating impact these missing signals have on running testcases.
From library documentation
https://docs.python.org/3/library/signal.html#signal.alarm
Windows OS does NOT implement signal.SIGALRM.

signal.SIGALRM
Timer signal from alarm(2).
Availability: Unix.

(2b) **No keywords found**.  This may be the result of relative Linux (Unix) Vs. Windows path separator '/'. For example code
`Resource           ../../lib/dmtf_tools_utils.robot
Resource           ../../lib/bmc_redfish_resource.robot
Resource           ../../lib/bmc_redfish_utils.robot`


Setup failed:
No keyword with name 'Redfish.Login' found.

Also teardown failed:
Several failures occurred:
1) No keyword with name 'FFDC' found.
2) No keyword with name 'Set FFDC Defaults' found.
3) AttributeError: module 'gen_print' has no attribute 'is_dict'
4) Replacing variables from keyword return value failed: Resolving variable '${content["data"]}' failed: Variable '${content}' not found.
5) TypeError: Expected argument 1 to be a list or list-like, got None instead.
6) Value of variable '@{dump_entries}' is not list or list-like.

**Comment by peterp-ibm** [comment]
Run into more issues with *NUX specific  implementations
- Regex and scripts that expect bash shell
- failed: AttributeError: module 'signal' has no attribute 'SIGALRM'. And
failed: AttributeError: module 'signal' has no attribute 'SIGUSR1'

**Comment by peterp-ibm** [comment]
If Windows Host is needed, it is better to run with WLS (Windows Linux Subsystem) instead of modify code to run Windows Native.
I stop this activity here.

**Comment by gkeishin** [comment]
Thanks @peterp-ibm  for trying it out.
