### ISSUE TITLE
BMC:GUI: logs are created in status folder under /home/ubuntu/ when executing gui/test/gui_header/test_obmc_gui_ip_refresh_check.robot

### ISSUE THREAD

**Issue by rajesh-lega** [openbmc/openbmc-test-automation#2127]
logs are created in status folder under /home/ubuntu/ which is outside openbmc test automation folder when executing gui/test/gui_header/test_obmc_gui_ip_refresh_check.robot

when executing GUI, ipmi or redfish cmd, status folder is created under home/ubuntu which is not no a best practice. 
all the files created by script should be kept inside automation folder.

logs created in /home/ubuntu/status
* 10.0.124.111.Auto_reboot.cp_cleanup.211011.203344.status
*  10.0.124.111.Auto_reboot.cp_pre_boot.211011.201927.status
* 10.0.124.111.Auto_reboot.cp_setup.211011.201926.status

**Comment by gkeishin** [comment]
```
status_dir_path = os.environ.get('STATUS_DIR_PATH', "")
if status_dir_path != "":
    status_dir_path = os.path.normpath(status_dir_path) + os.sep



lib/obmc_boot_test.py:status_dir_path = os.environ.get('STATUS_DIR_PATH', "")
lib/obmc_boot_test.py:    BuiltIn().set_global_variable("${STATUS_DIR_PATH}", status_dir_path)
lib/gen_call_robot.py:                       os.environ.get("STATUS_DIR_PATH",

```

so by default, it uses HOME if STATUS_DIR_PATH is not set in the env variable.  so this is right to do by default to HOME/status , instead of tossing inside the openbmc test directory.


however, the flexibility to target as non-env but as test variable is also needed where user can just

```
-v STATUS_DIR_PATH:<path>
```

so this support we can add but tweaking the code a bit which I'm working on.

**Comment by gkeishin** [comment]
Patch available @rajesh-lega   https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-test-automation/+/47749
