### ISSUE TITLE
selenium library issues with 2 new test cases in security/test_bmc_connections.robot

### ISSUE THREAD

**Issue by generatz** [openbmc/openbmc-test-automation#2161]
I'm seeing what appears to be a problem related to the selenium libraries with these two new test cases:
Security.Test Bmc Connections.Test Stability On Large Number Of Wrong Login Attempts To GUI
Security.Test Bmc Connections.Test BMC GUI Stability On Continuous Refresh Of GUI Home Page

Here is what the first one reports:
```
Multiple keywords with name 'Open Browser' found. Give the full name of the keyword you want to use:
    Selenium2Library.Open Browser
    SeleniumLibrary.Open Browser
```
The second one has the same report as shown above, plus:
```
Also teardown failed:
Multiple keywords with name 'Close All Browsers' found. Give the full name of the keyword you want to use:
    Selenium2Library.Close All Browsers
    SeleniumLibrary.Close All Browsers
```
I have tried two different python virtual environments with versions 3.6.9 and 3.9.10, but I get identical fails with both.

Anyone else seeing this?

**Comment by gkeishin** [comment]
Ideally, we shouldn't see this unless we installed both old and new packages are installed Selenium2Library / SeleniumLibrary causes it to fail to reference it.  However, it is safe to either remove the older one or take care in the code to explicitly reference it, 

@prkatti1  ^^^

**Comment by gkeishin** [comment]
Reference:  https://robotframework.org/Selenium2Library/Selenium2Library.html

NOTE: Selenium2Library has been renamed to [SeleniumLibrary](https://github.com/robotframework/SeleniumLibrary) since version 3.0. Nowadays [Selenium2Library](https://github.com/robotframework/Selenium2Library) is just a thin wrapper to SeleniumLibrary that eases with transitioning to the new project. See SeleniumLibrary and Selenium2Library project pages for more information.

**Comment by gkeishin** [comment]
Fix in review  https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-test-automation/+/51321

@generatz  

FYI @prkatti1 @swe12345
