### ISSUE TITLE
Ipmi.Test Ipmi User.Verify IPMI Root User Password Change teardown truncates long passwords

### ISSUE THREAD

**Issue by generatz** [openbmc/openbmc-test-automation#2192]
In the test `Ipmi.Test Ipmi User.Verify IPMI Root User Password Change` teardown the original password is restored by calling 
`Set Default Password For IPMI Root User`

`Set Default Password For IPMI Root User` restores the password with the following code:
```
    ${result}=  Run External IPMI Standard Command
    ...  user set password ${root_userid} ${OPENBMC_PASSWORD}
    ...  P=${valid_password}
```
This truncates the password if it is more than 16 characters. 

Workaround: Modify above code as follows:
```
    ${result}=  Run External IPMI Standard Command
    ...  user set password ${root_userid} ${OPENBMC_PASSWORD}
    ...  P=${valid_password} 20
```

**Comment by gkeishin** [comment]
@rahulmah Please take a look

**Comment by matthewfischer** [comment]
I think ipmitool is smart enough to handle this on its own without passing in 20.  Here is setting a 17 character password:

`ipmitool -p 6623 -C 17 -H 192.168.4.48 -I lanplus -U root -P 0penBmc user set password 10 kQLMSOGJL3CuW9EWZ`

And then using it just fine.  No need to pass in the password length in the above command.

`ipmitool -p 6623 -C 17 -H 192.168.4.48 -I lanplus -U mike -P kQLMSOGJL3CuW9EWZ user list`

If you pass in 16 when you set the password you get truncation but otherwise I think it defaults to 20 at least with a modern version of ipmitool.

**Comment by gkeishin** [comment]
This was on older codes in firmware support when he was testing it and was just a recommendation to improvise the test code handling it.   We will close this old ticket and we don't plan to work on it.
