### ISSUE TITLE
Verify No BMC Dump And Application Failures

### ISSUE THREAD

**Issue by justin0309** [openbmc/openbmc-test-automation#2212]
1. BMC dump(s) were not deleted as expected 200 != 404
2. I have been unable to find a solution to this error. I wonder if the delete bmc dump action was omitted in the test steps?

**Comment by gkeishin** [comment]
@manashsarma @rahulmah care to respond to this ?

**Comment by manashsarma** [comment]
Hello, @justin0309 , 404 is not found. It looks like that, just after generation , the BMC dump got offloaded to HMC (if an HMC is connected) or to Host OS (if Host OS is running). Can you please confirm. Also, can you please send me the testcase code snippet ?

**Comment by justin0309** [comment]
1. My idea is that this test item is to check whether the dump entry directory is empty, right?
2. I try to use the following command but there is no response and cannot be deleted
$ curl -k -H "X-Auth-Token: $token" -H "Content-Type: application/json" -X POST -d '{"data" : []}' https://${bmc} /xyz/openbmc_project/logging/entry/1/action/Delete

$ curl -k -H "X-Auth-Token: $token" -H "Content-Type: application/json" -X POST -d '{"data" : []}' https://${bmc} /xyz/openbmc_project/logging/action/DeleteAll

3. The attached picture is my robot test case

![image](https://github.com/openbmc/openbmc-test-automation/assets/109942943/0b864fab-64c4-40e9-8eaf-b5203c869844)

**Comment by manashsarma** [comment]
Above testcase does not attempt to delete a bmc dump.  It verifies no BMC dump there. Also we are supporting now redfish based URIs.

**Comment by gkeishin** [comment]
Thank you @manashsarma .. 

@justin0309  Yes the above test is a simple code check that can be used to look up if there are some dumps that have not been deleted and fail if it finds stray dumps left over on your system. So you can use this test to do that only. 

If your system is running with Redfish use this parameter in CLI when running it
```
-v REDFISH_SUPPORT_TRANS_STATE:1
```

Which will force the test to check via redfish API instead of old legacy REST.  You should add this parameter by default if running in Redfish.

**Comment by gkeishin** [comment]
@justin0309 I hope all is well. if you have further queries on it, feel free to comment. Thanks

**Comment by gkeishin** [comment]
Closing this ticket.
