### ISSUE TITLE
Test PostCodes When Host Reboot

### ISSUE THREAD

**Issue by justin0309** [openbmc/openbmc-test-automation#2228]
After restarting, postal code cannot be obtained. I can’t see what the error is in the log.

![image](https://github.com/openbmc/openbmc-test-automation/assets/109942943/bc317f06-b9ae-4e22-93db-2c92e7f0e7f0)

![image](https://github.com/openbmc/openbmc-test-automation/assets/109942943/f3c072f2-e6c2-4e1c-bdf4-9d7b5c7c992e)

Test PostCodes When Host Reboot
    [Documentation]  Initiate Host reboot the system and verify PostCodes from host are logged.
    [Tags]  Test_PostCodes_When_Host_Reboot

    # Boot to runtime and clear post codes.
    Redfish Power On  stack_mode=skip
    Redfish Clear PostCodes

    RF SYS GracefulRestart
    ${post_code_list}=  Redfish Get PostCodes
    Rprint Vars  post_code_list

    ${post_codes}=  Redfish.Get Properties
    ...  /redfish/v1/Systems/system/LogServices/PostCodes/Entries
    Log To Console  BIOS POST Codes count: ${post_codes['Members@odata.count']}
    Should Be True  ${post_codes['Members@odata.count']} >= 1  msg=No BIOS POST Codes populated.

**Comment by gkeishin** [comment]
@aravinth0510 can u look at this ?

**Comment by aravinth0510** [comment]
Hi @gkeishin , 
I tried running the same test. I can see post code generated in /system/LogServices/PostCodes/Entries after host system reboot in my environment. 
 But From the screenshot what Justin has shared, I could see that the post code entries collection is empty after system reboot. Ideally RF SYS GracefulRestart should have triggered some post code entries, since the system powers on from off state. The firmware behaviour is different and there is no change required from the test script.

**Comment by justin0309** [comment]
Hi,@Ara

**Comment by aravinth0510** [comment]
Hi @justin0309 ,  I have tested the code base in master version, and the keyword RF SYS GracefulRestart worked fine for me. Yes, the post code entries should be posted after the host is powered on ideally. And I can see that, the TC "Test PostCodes When Host Boots" is PASS for you as well. 

 As you have pointed, in your case RF SYS GracefulRestart did not power on the host system after off. So, I think the firmware you are using is not working as expected and hence you are not seeing post code entries getting populated after host reboot. So there is nothing I could do to help you regarding the firmware issue. @gkeishin kindly share your thoughts on this.
