### ISSUE TITLE
Test Redfish Managers Bmc Network Conf: Variable '${ip_addr}' not found.

### ISSUE THREAD

**Issue by jordanhong7709** [openbmc/openbmc-test-automation#2233]
I am testing Test Redfish Managers, and the test item (Bmc Network Conf) has a Variable '${path}' not found error in Suite Setup Execution. How can I solve this problem?
![image](https://github.com/openbmc/openbmc-test-automation/assets/140059050/8c0c6dd1-dfa3-45e3-bf22-6a2059264e76)
The version I'm currently using is as follows:
Python 3.10.13
Robot Framework 5.0.1 (Python 3.10.13 on linux)
I tried to upgrade or downgrade the robot framework, but I got the same error message. Do you have any suggestions?

**Comment by gkeishin** [comment]
@anvesh001 any new update you were looking earlier? any fix needed coming in ?

**Comment by jordanhong7709** [comment]
@prkatti1 I have not found any updates related to this issue. When using a static IP address, Suite Setup Execution errors will be ignored. Can I only use the static IP status for Bmc Network Conf testing?

**Comment by gkeishin** [comment]
@jordanhong7709  Commit https://gerrit.openbmc.org/c/openbmc/openbmc-test-automation/+/68246

**Comment by prkatti1** [comment]
@jordanhong7709 yeah, if the setup is already static suite setup does not do much. If system is in dhcp mode it'll capture network configurations & convert system configuration from dynamic to static.
There was small issue in library whch was designed long back, it is fixed in above commit.
Let me know if you need any further info.
