### ISSUE TITLE
Jan Support: Run loop test, evaluate test results, open issues, update #220 - Palmetto

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#259]

**Comment by sivassrr** [comment]
Expectation is to run loop test and evaluate the test results and open issues accordingly.
Also update the status in #220

**Comment by SrideviRamesh** [comment]
10th Jan - Palmetto CT result  with build #434

BMC codeupdate : good
PNOR update: good
CT: 144 TC , 3 failed (CT Run triggered excluding TC related to power on/off due to openbmc/issues#916)
2 TC failed to detect presence filed for chassis, system (openbmc/issues#960)
1 TC failed due to TC related to Association with virtual sensor

11th jan Palmetto CT result  with build #v1.99.0-377
BMC codeupdate : good
CT: 157 TC, 8 TC failed
8 TC are failed due to BOOTing issues

**Comment by SrideviRamesh** [comment]
12th jan Palmetto CT result with build #v1.99.0-383
BMC codeupdate : good
CT: 165 TC, 10 TC failed
10 TC are failed due to BOOTing issues & other known issues

**Comment by SrideviRamesh** [comment]
14th jan Palmetto CT result with build #276 v1.99.0-385
BMC codeupdate : good
CT: 144, 5 TC failed (Triggered CT RUN excluding TC which are related to BMC power off/on)
4 TC failed due to known issue, one TC DIMM3_present failed intermittently. Will be updating palmetto to latest build & check if the issues is repeated or not

**Comment by SrideviRamesh** [comment]
17th jan Palmetto CT result with build #"v1.99.0-392
BMC codeupdate : good
CT: 144, 5 TC failed (Triggered CT RUN excluding TC which are related to BMC power off/on)

**Comment by SrideviRamesh** [comment]
18th jan Palmetto CT result with build #v1.99.0-394
Pnor update: good with build palmetto #255
CT: 146, All TC passed (Triggered CT RUN excluding TC which are related to BMC power off/on)

**Comment by SrideviRamesh** [comment]
19th jan Palmetto CT result with build #279 v1.99.0-400
BMC codeupdate : good
CT: 160, 8 TC failed due to BOOTING issue

**Comment by sivassrr** [comment]
Could you update issue # for Booting issue

**Comment by SrideviRamesh** [comment]
20th jan palmetto CT result with build #v1.99.0-421
BMC codeupdate : good
CT 143 TC, All TC PASSED (Triggered CT RUN excluding TC which are related to BMC power off/on)

**Comment by SrideviRamesh** [comment]
23rd jan palmetto CTresult with build #v1.99.0-425
BMC codeupdate : good
CT 143 TC, All TC PASSED (Triggered CT RUN excluding TC which are related to BMC power off/on)
Issues regarding host boot is logged in https://github.com/openbmc/openbmc/issues/861
and https://github.com/openbmc/openbmc/issues/916

**Comment by SrideviRamesh** [comment]
25th jan palmetto VERSION_ID= #475-b3ff4009f88634
BMC Codeupdate : Failed
Issue is raised regarding the failure https://github.com/openbmc/openbmc/issues/1030

**Comment by SrideviRamesh** [comment]
27th jan palmetto CT Result with build #v1.99.1-43
BMC codeupdate : good

**Comment by SrideviRamesh** [comment]
30th jan palmetto CT Result with build #v1.99.1-45
BMC codeupdate : good
CT 170 TC, 155 PASS, 15 FAIL

8 TC failed due to HOST_BOOT issues as mentioned below

1.	power on test
2.	Verify CPU VPD Properties
3.	Verify Fan VPD Properties
4.	Verify Memory Buffer VPD 
5.	minimal core inventory
6.	minimal cpu inventory
7.	Get OCC status
8.	Get System Power Consumption

2 TC Persist ONETIME Boot Policy After Reset & Persist PERMANENT Boot Policy After Reset failed due to reboot issue
