### ISSUE TITLE
Feature: Replacement for ipmitool with commands like dbus-send, dbus-btrbridge etc..

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc-test-automation#40]
It has been decided not to have a bin inside the tools directory of github.
To overcome the use of ipmitool, we need to come up with an alternate method. 
We can use dbus-send, dbus-btrbridge or other command if any available.

**Comment by sivassrr** [comment]
@williamspatrick : When this discussion happened, Not there got the background about this issue. Make sense and I agree.

**Comment by vishwabmc** [comment]
@sivassrr : We need to discuss how are we trying to use dbus-send in place of ipmitool. dbus-send does not host any of the dbus services and hence it is not an option at all on a QEMU.

On a real HW tho, we can use dbus-send to fire a signal that IPMI daemon can catch ( we need to see how to send a ipmi payload as stream of bytes ) but then a response to the IPMI message will goto bt-bridge since BT-Bridge is the one that is implementing that method, Since BT bridge did not even initiate the IPMI transaction, we need to see how bt-bridge will react to this.

**Comment by sivassrr** [comment]
Sure, Vishwa, certainly want to discuss on this. Another thought dbus-send not a debug tool? will customer uses it. If we use REST API then we are verifying customer method as well, right

**Comment by vishwabmc** [comment]
@sivassrr : To use dbus-send, you need to be on the BMC.. So I would not see this as a customer usecase. If you can test everything using REST ( the customer way ) then we should be all good.

@williamspatrick Do you have any comments ?

**Comment by williamspatrick** [comment]
Any dbus interface should be available over REST as the 'test' user, which we have yet to define and add.  For now, 'root' has permissions to run any REST interface.

I am not sure if we should convert the tests over to using REST though.  Can we enumerate the tests that ipmitool is needed for?  Ideally, I think we would put the ipmitool into a development tarball that can be side-loaded for test purposes.

**Comment by vishwabmc** [comment]
@williamspatrick  I like the idea of enumerating the tests that need the ipmitool and we can then evaluate REST v/s dbus-send.
