### ISSUE TITLE
[Barreleye] Variable '${TURBO_SETTING}' not found.

### ISSUE THREAD

**Issue by swe12345** [openbmc/openbmc-test-automation#745]
- Variable '${TURBO_SETTING}' not found.
- Moving TURBO SETTINGS from the Suite Setup to Test Setup as few Test cases are failing in tests/test_sensors.robot

**Comment by gkeishin** [comment]
This is not a bug.. this is because when the poweron failed, the variable would not be set thats all.

**Comment by rahulmah** [comment]
@gkeishin : In barreleye, turbo setting url(/org/openbmc/sensors/host/TurboAllowed ) is not there. Due to this suite setup is failing in sensor which checks for this url. So we should move the turbo setting check from suite setup to test cases related to turbo setting. Please reopen the issue for Sweta to fix.

**Comment by swe12345** [comment]
bash-4.1$ curl -c cjar -b cjar -k -H "Content-Type: application/json" -X GET https://xx.xx.xx.xx//org/openbmc/sensors/host/TurboAllowed/
{
  "data": {
    "description": "org.freedesktop.DBus.Error.FileNotFound: path or object not found: /org/openbmc/sensors/host/TurboAllowed"
  },
  "message": "404 Not Found",
  "status": "error"

**Comment by swe12345** [comment]
Moving the following test cases into the skip list:

- Verify Enabling OCC Turbo Setting Via IPMI
- Verify Disabling OCC Turbo Setting Via IPMI
- Verify Setting OCC Turbo Via REST

**Comment by swe12345** [comment]
https://gerrit.openbmc-project.xyz/#/c/5078
